name: b2b
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter: 
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: 4.6.5
  dio: ^4.0.6
  nhost_sdk: ^3.0.4
  nhost_flutter_graphql: ^2.1.0
  nhost_flutter_auth: ^2.0.4
  google_fonts: ^3.0.1  
  flutter_svg: ^1.1.6
  intl: ^0.18.0
  http: ^0.13.5
  dynamic_height_grid_view: ^0.0.3
  image_picker: ^0.8.6
  badges: ^3.0.2
  transparent_image: ^2.0.0
  
dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

assets:
  - web/assets/

