name: b2b
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter: 
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: 4.6.5
  get_storage: 2.0.3
  google_fonts: ^3.0.1  
  flutter_svg: ^1.1.6
  data_table_2: ^2.3.8

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

assets:
  - web/assets/

